[tox]
basepython = python3.14
envlist =
    lint
    style
    typing
    uvlock
    docrendering
    py310-django22
    py{310,312}-django32
    py{310,312,314,315}-django{42,52}
    py{312,314,315}-django60
labels =
    check = lint, style, typing, uvlock, docrendering, deploycheck

[testenv]
labels =
    py3{10,12,14,15}: test
package = wheel
no_default_groups = true
dependency_groups = dev
constrain_package_deps = True
deps =
    django22: setuptools<81
    django22: django~=2.2.0
    django32: django~=3.2.0
    django42: django~=4.2.0
    django52: django~=5.2.0
    django60: django~=6.0.0
setenv =
    PYTHONPATH=.
commands =
    pytest {posargs:--cov=drf_jwt_2fa}

[testenv:lint]
package = skip
commands =
    ruff check {posargs}

[testenv:style]
package = skip
commands =
    ruff format --check --diff {posargs}

[testenv:typing]
package = deps-only
commands =
    mypy {posargs:.}

[testenv:uvlock]
package = skip
dependency_groups =
commands = uv lock --check

[testenv:docrendering]
package = skip
dependency_groups =
deps = readme_renderer[md]
allowlist_externals = ./check-text-docs
commands =
    ./check-text-docs {posargs:README.rst ChangeLog.rst}

[testenv:deploycheck]
package = wheel
setenv =
    PYTHONPATH=.
    DJANGO_SETTINGS_MODULE=test_deploy_settings
commands =
    django-admin check --deploy
