[tox]
basepython = python3.14
envlist =
    style
    uvlock
    py310-django22
    py{310,312}-django32
    py{310,312,314}-django{42,52}
    py{312,314}-django60

[testenv]
no_default_groups = true
dependency_groups = dev
deps =
    django
    djangorestframework>=3.0
    djangorestframework-simplejwt>=5.1
    django22: setuptools<81
    django22: django~=2.2.0
    django32: django~=3.2.0
    django42: django~=4.2.0
    django52: django~=5.2.0
    django60: django~=6.0.0
setenv =
    PYTHONPATH=.
commands =
    pytest {posargs:--cov=drf_jwt_2fa}

[testenv:style]
skip_install = True
commands = ruff check {posargs}

[testenv:uvlock]
dependency_groups =
commands = uv lock --check
