---
name: "Tests and Checks"
on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main, test]
  workflow_dispatch:

jobs:
  tests:
    name: "Tests: Py${{matrix.python}}-Django${{matrix.django}}"
    strategy:
      matrix:
        python: ["3.10", "3.12", "3.14", "3.15.0-alpha.8"]
        django: ["2.2", "3.2", "4.2", "5.2", "6.0"]
        exclude:
          - {python: "3.10", django: "6.0"}
          - {python: "3.12", django: "2.2"}
          - {python: "3.14", django: "2.2"}
          - {python: "3.14", django: "3.2"}
          - {python: "3.15.0-alpha.8", django: "2.2"}
          - {python: "3.15.0-alpha.8", django: "3.2"}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{matrix.python}}

      - name: Install Tox and tox-uv
        run: pip install tox tox-uv

      - name: Set TOXENV
        run: >-
          echo "TOXENV=py${{matrix.python}}-django${{matrix.django}}"
          | sed -E 's/\.0-(alpha|beta)[.]?[0-9]+//g;s/[.]//g' >> $GITHUB_ENV

      - name: Test with Tox
        run: tox
        env:
          TOXENV: ${{env.TOXENV}}

      - name: Install git, curl and coverage for codecov action
        run: sudo apt-get install -y git curl && pip install coverage

      - name: Upload coverage data to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  checks:
    name: "Check: ${{matrix.toxenv}}"
    strategy:
      matrix:
        toxenv: [lint, style, typing, uvlock, docrendering]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install Tox and tox-uv
        run: pip install tox tox-uv

      - name: Run the check with Tox
        run: tox
        env:
          TOXENV: ${{matrix.toxenv}}
