---
name: "Release"
on:
  push:
    tags: ["v[0-9]*.*"]
  workflow_dispatch:

env:
  PYPI_URL: https://upload.pypi.org/legacy/
  TESTPYPI_URL: https://test.pypi.org/legacy/

jobs:
  publish:
    name: "Publish to ${{matrix.target}}"
    strategy:
      matrix:
        target: ["PyPI", "TestPyPI"]
        event: ["${{github.event_name}}"]
        exclude:
          - {target: "PyPI", event: "workflow_dispatch"}
          - {target: "TestPyPI", event: "push"}

    runs-on: ubuntu-24.04
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          python-version: "3.14.4"

      - name: Set modified version for TestPyPI
        if: matrix.target == 'TestPyPI'
        # Replace default-version in pyproject.toml and force
        # versioningit to use it by removing the .git directory
        run: |
          sed -i "s/post0+unknown/post0.dev$(date +%s)/" pyproject.toml
          rm -rf .git

      - name: Build sdist and wheel
        run: uv build

      - name: Publish to ${{matrix.target}}
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
        with:
          repository-url: >-
            ${{matrix.target == 'PyPI' && env.PYPI_URL || env.TESTPYPI_URL}}
